[package]
name = "mimp"
version = "0.1.0"
authors = ["Maki <mxmcube@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.21.1"
num-complex = "0.2.1"
clap = "2.33.3"